import 'dotenv/config';
import type { ExpoConfig } from 'expo/config';

/**
 * APNs environment baked into the iOS entitlements by onesignal-expo-plugin.
 * It MUST match the provisioning profile the build is signed with:
 *   - EAS `development` profile (development cert)  → 'development' (APNs sandbox)
 *   - EAS `preview` / `production` (ad-hoc, App Store) → 'production'
 * TestFlight and App Store builds are production-signed, so 'production' is the
 * default; the `development` build profile sets APNS_MODE=development.
 */
const APNS_MODE = process.env.APNS_MODE === 'development' ? 'development' : 'production';

export default (): ExpoConfig => ({
  name: '101Lab',
  slug: 'greenbridge',
  scheme: 'greenbridge',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  userInterfaceStyle: 'light',
  ios: {
    bundleIdentifier: 'com.greenbidz.bridge',
    supportsTablet: false,
    config: {
      // No proprietary/non-exempt encryption — only standard HTTPS. Declaring it
      // here stops App Store Connect asking for export compliance every upload.
      usesNonExemptEncryption: false,
    },
    infoPlist: {
      // Purpose strings App Review reads verbatim. Be specific about WHY —
      // generic strings ("needs camera access") are a common rejection.
      NSCameraUsageDescription:
        'Allow 101Lab to use the camera so you can photograph equipment and have the AI identify it and draft a listing or enquiry for you.',
      NSPhotoLibraryUsageDescription:
        'Allow 101Lab to access your photos so you can attach existing equipment images to a listing, a request, or a message.',
    },
    // Apple ITMS-91053: SDKs that touch "required reason" APIs must be declared
    // or the upload is rejected by email. Covers React Native + MMKV + Expo FS.
    privacyManifests: {
      NSPrivacyAccessedAPITypes: [
        {
          // File timestamps — expo-file-system / MMKV storage files.
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryFileTimestamp',
          NSPrivacyAccessedAPITypeReasons: ['C617.1'],
        },
        {
          // NSUserDefaults — React Native core + OneSignal.
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryUserDefaults',
          NSPrivacyAccessedAPITypeReasons: ['CA92.1'],
        },
        {
          // Free disk space — checked before writing image/document caches.
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryDiskSpace',
          NSPrivacyAccessedAPITypeReasons: ['E174.1'],
        },
        {
          // System boot time — used for monotonic timers.
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategorySystemBootTime',
          NSPrivacyAccessedAPITypeReasons: ['35F9.1'],
        },
      ],
    },
  },
  android: {
    package: 'com.greenbidz.bridge',
    // Strip permissions we never use, so the Play listing's "Permissions" section
    // stays honest and reviewers have nothing to query. `blockedPermissions` emits
    // tools:node="remove", which wins over anything a library manifest merges in —
    // the Android counterpart of passing `false` to the iOS permission plugins.
    //
    // Both of these were in the app manifest generated by the (stale, untracked)
    // 2026-05-29 prebuild: RECORD_AUDIO from when expo-camera's recordAudioAndroid
    // still defaulted true, and SYSTEM_ALERT_WINDOW ("Display over other apps"),
    // which React Native only needs in its debug source set.
    blockedPermissions: [
      'android.permission.RECORD_AUDIO',
      'android.permission.SYSTEM_ALERT_WINDOW',
    ],
    adaptiveIcon: {
      backgroundColor: '#FFFFFF',
      foregroundImage: './assets/images/android-icon-foreground.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
  },
  web: {
    bundler: 'metro',
    output: 'static',
    favicon: './assets/images/favicon.png',
  },
  plugins: [
    'expo-router',
    [
      'expo-camera',
      {
        cameraPermission:
          'Allow 101Lab to use the camera so you can photograph equipment and have the AI identify it and draft a listing or enquiry for you.',
        // The scan flow captures stills only — never audio. `false` DELETES the
        // key (see IOSConfig.Permissions.applyPermissions) instead of falling
        // back to the plugin's generic default, so the store build does not
        // declare a microphone permission it never requests.
        microphonePermission: false,
        recordAudioAndroid: false,
      },
    ],
    [
      'expo-image-picker',
      {
        photosPermission:
          'Allow 101Lab to access your photos so you can attach existing equipment images to a listing, a request, or a message.',
        // This plugin adds android.permission.RECORD_AUDIO unless explicitly told
        // not to — it was the source of the microphone permission in the release
        // manifest, not expo-camera. Passing `false` both skips it and makes the
        // plugin block it, so no other package can reintroduce it.
        microphonePermission: false,
      },
    ],
    [
      'expo-secure-store',
      {
        // No biometric-gated reads anywhere in the app (`requireAuthentication`
        // is never used), so drop the Face ID declaration.
        faceIDPermission: false,
      },
    ],
    'expo-notifications',
    'expo-localization',
    'expo-image',
    'expo-web-browser',
    [
      'expo-location',
      {
        // Foreground only — used to auto-fill the listing's pickup address.
        locationWhenInUsePermission:
          'Allow 101Lab to use your location to auto-fill the pickup address of a listing.',
        // `false` deletes these keys. App Review scrutinises "Always" location
        // hardest, and we never request always-authorization or background
        // location — declaring only WhenInUse keeps the ask honest. Motion is
        // an expo-location default the app never uses.
        locationAlwaysAndWhenInUsePermission: false,
        locationAlwaysPermission: false,
        motionUsagePermission: false,
        isAndroidBackgroundLocationEnabled: false,
      },
    ],
    [
      'expo-splash-screen',
      {
        backgroundColor: '#002855',
        image: './assets/images/greenbidz_logo.png',
        imageWidth: 220,
        resizeMode: 'contain',
      },
    ],
    [
      'onesignal-expo-plugin',
      {
        mode: APNS_MODE,
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
  extra: {
    eas: {
      projectId: '57cd3db7-90b1-4b57-a723-679bfe81ef69',
    },
    GREENBIDZ_API_URL: process.env.GREENBIDZ_API_URL,
    // ASSISTANT (Python FastAPI) base URL — chat/detect stream, WTB, handoff.
    // Distinct from GREENBIDZ_API_URL (NODE). Default prod; override with
    // AI_BASE_URL in .env (e.g. https://dev-ai.greenbidz.com for the dev stack).
    AI_BASE_URL: process.env.AI_BASE_URL ?? 'https://ai.greenbidz.com',
    QUIPPY_API_URL: process.env.QUIPPY_API_URL,
    X_SYSTEM_KEY: process.env.X_SYSTEM_KEY,
    SITE_TYPE: process.env.SITE_TYPE ?? 'LabGreenbidz',
    WEB_APP_URL: process.env.WEB_APP_URL,
    // 101 Lab marketplace web origin for the Browse-tab WebView. Default prod
    // (https://101lab.co) applied in getMarketplaceUrl(); override here.
    MARKETPLACE_URL: process.env.EXPO_PUBLIC_MARKETPLACE_URL,
    SENTRY_DSN: process.env.SENTRY_DSN,
  },
});
