/**
 * W4 (scan_v3) — country list ported verbatim from
 * `GreenBridgeSeller/src/pages/new-submission-upload/constants/countries.ts`.
 * Replaces the free-text country input in `LocationCard` with a search-filter
 * sheet picker.
 *
 * Note: the verbatim web list omits Taiwan, China, Japan, India, Thailand,
 * Vietnam, Indonesia, Malaysia, Singapore-region neighbors — Singapore is
 * present but others are not. The backend defaults `country: 'Taiwan'` when
 * AI omits the field (`controller/wordPress.js:452-459`), which conflicts
 * with this list. Web has the same conflict today; flagging here so a
 * follow-up can decide whether to extend the list or relax the picker to
 * also accept free-text fallback. Verbatim port keeps mobile + web in lockstep.
 */
export const COUNTRY_OPTIONS = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Argentina',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Belgium',
  'Bolivia',
  'Brazil',
  'Bulgaria',
  'Cambodia',
  'Canada',
  'Chile',
  'Colombia',
  'Croatia',
  'Czech Republic',
  'Denmark',
  'Ecuador',
  'Egypt',
  'Estonia',
  'Ethiopia',
  'Finland',
  'France',
  'Germany',
  'Ghana',
  'Greece',
  'Guatemala',
  'Hong Kong',
  'Hungary',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Libya',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Mexico',
  'Mongolia',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Panama',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Saudi Arabia',
  'Serbia',
  'Singapore',
  'Slovakia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sweden',
  'Switzerland',
  'Syria',
  'Tanzania',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Yemen',
  'Zambia',
  'Zimbabwe',
] as const;

export type CountryOption = (typeof COUNTRY_OPTIONS)[number];
